creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    age: >-
      age1u8dqa38qkztrzcuppkezy7mt7500aa0yex65e7h7qxyze59sdgpssksa62
      age14t2x3suh4qec8rwmls580er6fef9ct4du6vcyqlv874qkvknf4uqtkk3r7
