creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    age: >-
      age1u8dqa38qkztrzcuppkezy7mt7500aa0yex65e7h7qxyze59sdgpssksa62,
      age14t2x3suh4qec8rwmls580er6fef9ct4du6vcyqlv874qkvknf4uqtkk3r7,
      age1ff0ec8nqfjaetdcgszfrjd03uuptjuepp4l32ha7x6lplzrflg4q74cah5,
      age1gvd83mnsq3wpxtcncsr26r9eyzfv8s7vwcz4a37wd0vaum4x95nsnnate3
