---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets-operator
  namespace: default
spec:
  destination:
    namespace: sops-secrets-operator
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: sops-secrets-operator
    repoURL: https://isindir.github.io/sops-secrets-operator/
    targetRevision: 0.25.0
    helm:
      values: |-
        secretsAsEnvVars:
          - name: SOPS_AGE_KEY
            secretName: sops-age-key
            secretKey: age-key


---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cloudflare-sopssecret
  namespace: external-dns
spec:
  secretTemplates:
    - name: cloudflare-api-token-secret
      stringData:
        cloudflare_api_token: ENC[AES256_GCM,data:ly2j7l6peZsYT8h9vXUHSmLugag9OxEJSGMu0QNz4h4jkpp7amahpg==,iv:nEe1oG3fncXFO3EwNgXz7gijL3R5Y8nAD926OD3xBoc=,tag:GWu8Ipkd9ZGiV96BbE3JoQ==,type:str]
sops:
  age:
    - recipient: age17p9fjp7yvq3yqzjhjpf3zetv68878tguj5d6r3x3mdp7hv2sqevqgyg4au
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZmI2eVRMNGpES0VTRDFo
        RFhLRytZZ0V3Vi9PZm96TEhQdzhZNFZLeWtNCjNybE1qbGxyb1NMeVZHUnhmYzhp
        VHk1b3dtWVhSeTJXM0FaUmpJZXNoZVUKLS0tIGJ1ekMzTmwyUkVpWUN4M2Vtb3NB
        c2FQOWpZYWpqMXdCOGd2VW1PTDQwV00KjvGhxHe0CQuakntlwDSBqAu1K2dYmswW
        M42LVwxvSI+MfmiSCiTNCnINiFAYim+dv9Jv3Xc9h9SDvgPg+4ezAA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1u8dqa38qkztrzcuppkezy7mt7500aa0yex65e7h7qxyze59sdgpssksa62
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbzk0RzNSMmdCRDdYUW9m
        dHZ1aDY2ZE1FdG1HcHN3K0lmZkphcXVKOUMwCllrWVZhdDRrdmJ5dEY5MUl2YlRL
        MG85d3VBNEtGV2RLMkk5NkRQbUZQMnMKLS0tIDBrdVJkZEcyZTlXZjFhVjkwdUkx
        eVk1THgwdytLZG4xOGlieTFxd1plKzgKihBPOljDd1PzTte92GE5twP55XNbkbrp
        yJz1MvDHhGU3MMt7ch/gPYvqUnTvs/0I4B2549JZvrYJQeCyW6/Bfw==
        -----END AGE ENCRYPTED FILE-----
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
