# vim: ts=2:sw=2:et
{
  config,
  pkgs,
  lib,
  system,
  ...
}:
with lib; let
  cfg = config.wheat;
  isDarwin = if lib.hasSuffix "darwin" system then true else false;

in {
  options = {
    wheat = with types; {
      enable = mkEnableOption "Enable";
      secrets.enable = mkEnableOption "Enable SOPS secrets";
      nameservers = mkOption {
        description = "DNS Servers";
        type = types.listOf types.str;
        default = [
          "1.1.1.1"
          "1.0.0.1"
        ];
      };
      user = with types; {
        name = mkOption {
          description = "Username to create";
          type = str;
        };
        hashedPassword = mkOption {
          description = "hashed password generated by mkpasswd";
          type = str;
        };
        extraGroups = mkOption {
          default = [
            "podman"
          ];
          description = "Additional groups to add the user to.";
          type = listOf str;
        };
        authorizedKeys = mkOption {
          type = listOf str;
          default = [
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ3x/dtivaU+bPMRYzY1O+XQPEGnBahNnh9sBZMrJrIX petee"  # x1
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBaGYqqLKVikzCKsRJqfPu4zsTCKCfCz9xnWYQJNep+v petee@x1"  # prob dead
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAMShYQQ6RsCgYUXKxaVYjjGcjvdB533v/wsdrYq7G/7 JuiceSSH"  # phone
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMjd2zJEmRiuqMJz2kC4ABIiSVE2HWdRPkZTmcAxp6GS petee@nixos" # nixos vm (ripper)
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL1SMCMFF12YYwlYGIi/UATCPTQ+PEdYOygGFouYrd5N petee@m3p" # lappy
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC1Xr2ircu0B1j+fmj8r1P5xtRi+LstqeXCJ7XIdhpyI nixos@nixos" # rpi?
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEMv8uBStPXcU4V5+7L6TpP08HhpG5vumutAFogVd0ca pete@m4" # litle mac
          ];
        };
      };
      fonts = mkOption {
        description = "fonts";
        type = types.listOf types.str;
        default = with pkgs; [
          nerd-fonts.fira-code
          nerd-fonts.droid-sans-mono
        ];
      };
      tailscale.enable = mkEnableOption "Enable tailscale";
    };
  };

  config = mkIf cfg.enable {
    programs.zsh.enable = true;
    users.groups.${cfg.user.name} = {};
    users.users.${cfg.user.name} = {
      inherit (cfg.user) name;
      # home = "/Users/${cfg.user.name}";
      home = if isDarwin then "/Users/${cfg.user.name}" else "/home/${cfg.user.name}";
      createHome = true;
      shell = pkgs.zsh;
      openssh.authorizedKeys.keys = cfg.user.authorizedKeys;
    } // lib.optionalAttrs isDarwin {
      isHidden = false;
    };
    services.openssh = {
      enable = true;
      ports = [ 22 ];
      settings = {
        PasswordAuthentication = false;
        AllowUsers = null;
        UseDns = true;
        X11Forwarding = false;
        PermitRootLogin = "no";
      };
    };

    fonts.packages = with pkgs.nerd-fonts; [
      fira-code
      droid-sans-mono
      symbols-only
      jetbrains-mono
    ];
    services.tailscale.enable = true;
    # services.tailscale.enable = cfg.enable;
    networking.nameservers = cfg.nameservers;
  };
}
